### PR TITLE
Update mihoyo links and cookie paths

### LINKED ISSUE #12: login information not found
forced to clear the cookies and login again almost every day

### LINKED ISSUE #13: Need to log in to hoyolab even though its already logged in
The bot doesnt detect the chrome version as i already have it logged in and when the bot runs it tells me that the cookie is not found and please log into hoyolab.
but i have already re logged in and clear the cookie and tried again and no avail.

### PR DESCRIPTION
**Pull request by igorgaming**
Closes #12
Closes #13

This PR:
- Updates `browser-cookie3` package to the latest version with updated cookie paths for latest version of chomium-based browsers
- Changes links for mihoyo check-in event
- Updates token cookie name to long-expired cookie

### CODE REVIEW

**Comment by SpaceofWeb** [comment]
Hi. Any progress on this?

**Comment by igorgaming** [comment]
> Hi. Any progress on this?

Hi, i think the owner of this repo is not active anymore. You can use my or other fork of this repo and compile it to the .exe file
(You can do it by using following command(you also need to pre-install all dependencies)):
- pyinstaller -F --windowed --paths .\venv\Scripts\Lib\site-packages\ .\main_windows.py

Or just install `compiled.rar` archive from https://github.com/igorgaming/hoyolab-daily-bot/releases/tag/Fix-browsers

P.s: i didnt test this well, but it works for me in Edge browser.

**Comment by SpaceofWeb** [comment]
> > Hi. Any progress on this?
> 
> Hi, i think the owner of this repo is not active anymore. You can use my or other fork of this repo and compile it to the .exe file (You can do it by using following command(you also need to pre-install all dependencies)):
> 
>     * pyinstaller -F --windowed --paths .\venv\Scripts\Lib\site-packages\ .\main_windows.py
> 
> 
> Or just install `compiled.rar` archive from https://github.com/igorgaming/hoyolab-daily-bot/releases/tag/Fix-browsers
> 
> P.s: i didnt test this well, but it works for me in Edge browser.

Wow. Thanks a lot. I tried it with 'firefox' and 'all' and get an error

image


I don't know python at all and spend few hours (before comment above) to compile your code but get numerous errors here and there. Last one was: 
`pip3.10.exe install -r requirements.txt`

```
Collecting PyInstaller==4.2
  Using cached pyinstaller-4.2.tar.gz (3.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
  ........
File "C:\Users\aaron_000\AppData\Local\Temp\pip-install-vqqj55ug\pyinstaller_fb788be63a6947e3b05387a05fc7fccf\PyInstaller.py", line 16, in <module>
          from PyInstaller.__main__ import run
      ModuleNotFoundError: No module named 'PyInstaller.__main__'; 'PyInstaller' is not a package
```

I used python 3.10.1, pip 22.3.1. Also tried to compile in macos but get the same error

I'll be grateful if you can help me a bit

**Comment by igorgaming** [comment]
@SpaceofWeb First error occurs at this line: https://github.com/igorgaming/hoyolab-daily-bot/blob/4ac82145d4dfe1ab2cc9d5f094f5f2f9020f2382/main_windows.py#L211
I also have this error on my pc, maybe because i am using Windows or smth like that.
You just need to run this script as administrator(check few lines above).

Packages in Python are little bit tricky, i think i also have this error, but i was able to bypass it in some way.
Try just run my compiled exe as administrator, its should be ok.

**Comment by SpaceofWeb** [comment]
> @SpaceofWeb First error occurs at this line: https://github.com/igorgaming/hoyolab-daily-bot/blob/4ac82145d4dfe1ab2cc9d5f094f5f2f9020f2382/main_windows.py#L211 I also have this error on my pc, maybe because i am using Windows or smth like that. You just need to run this script as administrator(check few lines above).
> 
> Packages in Python are little bit tricky, i think i also have this error, but i was able to bypass it in some way. Try just run my compiled exe as administrator, its should be ok.

Damn, I forgot I need to run it as admin, do not work in windows.
Yeah, as u said it worked well. Thanks a lot)

**Comment by Frenw0rld** [comment]
Does the script still work? Was trying to write an equivalent in another language, but so far unable to bypass the Cloudfront bot detection.

**Comment by igorgaming** [comment]
> Does the script still work? Was trying to write an equivalent in another language, but so far unable to bypass the Cloudfront bot detection.

Yeah, definetly works at least for me.

**Comment by igorgaming** [comment]
They added captcha to the daily check-in lol, any script not works anymore 😂

**Pull request closed without merging**
